# Package data — imported into build.py
PACKAGES = [
{
    "slug": "kashmir-paradise-getaway-5n-6d",
    "title": "Kashmir Paradise Getaway",
    "duration": "5 Nights / 6 Days",
    "route": "Srinagar – Gulmarg – Pahalgam – Sonmarg",
    "category": "Best Seller",
    "price": 24999, "old_price": 27999,
    "hero": IMG["dal_sunset"], "gallery": [IMG["gulmarg_gondola"], IMG["betaab1"], IMG["nishat_bagh"]],
    "meta_title": "Kashmir Tour Package 5 Nights 6 Days | Srinagar Gulmarg Pahalgam | Plan My Trip Kashmir",
    "meta_desc": "Book our best-selling Kashmir tour package (5N/6D) covering Srinagar, Gulmarg, Pahalgam & Sonmarg with houseboat stay, shikara ride & transfers. Prices up to 10% below the standard market rate.",
    "intro": "Our most-booked Kashmir trip package, built for first-time travellers who want to see the valley's four icons — Dal Lake, Gulmarg, Pahalgam and Sonmarg — without rushing. You spend a night aboard a traditional houseboat, ride the Gulmarg Gondola toward the Apharwat slopes, walk through the pine-lined meadows of Betaab and Aru, and end the day in Sonmarg beside the Sindh River, all on a fixed departure or private itinerary that our Srinagar-based team runs from arrival to airport drop.",
    "highlights": [
        "1 night aboard a deluxe houseboat on Dal Lake with a private shikara ride",
        "Gulmarg Gondola (Phase 1) cable-car ride toward Kongdoori",
        "Pahalgam sightseeing: Betaab Valley, Aru Valley and the Lidder riverside",
        "Half-day excursion to Sonmarg — Thajiwas Glacier viewpoint",
        "Srinagar Mughal Gardens: Nishat Bagh and Shalimar Bagh",
        "All airport/railway station transfers by private AC vehicle",
    ],
    "itinerary": [
        ("Day 1 — Arrival in Srinagar & Houseboat Check-in", "Land at Srinagar Airport, where our representative greets you and transfers you to your houseboat on Dal Lake. Spend the afternoon at leisure or take an optional shikara ride past the floating vegetable market. Evening tea is served on the houseboat deck as the sun sets over the Zabarwan hills. Overnight on the houseboat."),
        ("Day 2 — Srinagar Local Sightseeing & Mughal Gardens", "After breakfast, visit Nishat Bagh and Shalimar Bagh, the terraced Mughal gardens built on Dal Lake's eastern shore, followed by Chashme Shahi and a stop at Shankaracharya Hill for a panoramic view of the city. Return for a one-hour shikara ride through the lake's quieter channels in the evening. Overnight in Srinagar."),
        ("Day 3 — Srinagar to Gulmarg Day Excursion", "Drive roughly 50 km (about 1.5 hours) to Gulmarg, the 'meadow of flowers'. Take the Gulmarg Gondola cable car up to Kongdoori for views of the Apharwat range (Phase 2 ropeway to Apharwat is optional and paid directly at the counter, subject to weather). Explore the golf course and pine forest before returning to Srinagar by evening."),
        ("Day 4 — Srinagar to Pahalgam", "Drive to Pahalgam (about 90 km, 2.5–3 hours), stopping at the saffron fields of Pampore and the Awantipora ruins en route. Check in to your hotel and spend the evening walking along the Lidder River. Overnight in Pahalgam."),
        ("Day 5 — Pahalgam Valley Sightseeing & Sonmarg Transfer", "Visit Betaab Valley and Aru Valley by local taxi (included) before driving to Sonmarg via Srinagar. Sonmarg sits at the base of the Thajiwas Glacier and the road to Ladakh via Zoji La. Overnight in Sonmarg or Srinagar depending on hotel availability."),
        ("Day 6 — Departure", "After breakfast, transfer to Srinagar Airport or railway station for your onward journey, with fond memories of the valley and a printed photo voucher from our team."),
    ],
    "inclusions": [
        "5 nights accommodation (1 houseboat + 4 hotel) on double/twin sharing",
        "Daily breakfast and dinner (MAP plan)",
        "All transfers and sightseeing by private AC vehicle (Innova/Sumo/similar)",
        "1 hour shikara ride on Dal Lake",
        "Gulmarg Gondola Phase 1 ticket",
        "All applicable tolls, parking and driver allowance",
        "Dedicated trip coordinator on WhatsApp throughout your stay",
    ],
    "exclusions": [
        "Airfare/train fare to and from Srinagar",
        "Gulmarg Gondola Phase 2 (Apharwat) ticket — paid on the spot, weather dependent",
        "Pony/horse rides, sledging and other optional adventure activities",
        "Lunch and any meals not mentioned in inclusions",
        "Personal expenses, tips and travel insurance",
        "GST and anything not specifically mentioned as included",
    ],
    "faqs": [
        ("Is 5 nights 6 days enough to cover Kashmir?", "Yes — this is the most popular duration for a first Kashmir trip. It comfortably covers Srinagar, Gulmarg, Pahalgam and a Sonmarg excursion without feeling rushed. If you also want Ladakh or Vaishno Devi, ask us about our extended packages."),
        ("Can this package be customised?", "Yes. Every itinerary on this page is a starting template — we adjust the number of days in each destination, upgrade hotel categories, or add Ladakh, Doodhpathri or Vaishno Devi on request at no planning fee."),
        ("Is the houseboat safe and comfortable?", "We work only with registered houseboat owners on Dal Lake who meet Jammu & Kashmir Tourism's safety and hygiene standards. Rooms include attached bathrooms, running hot water and heating on request."),
    ],
},
{
    "slug": "kashmir-express-4n-5d",
    "title": "Kashmir Express",
    "duration": "4 Nights / 5 Days",
    "route": "Srinagar – Gulmarg – Pahalgam",
    "category": "Budget Friendly",
    "price": 17999, "old_price": 19999,
    "hero": IMG["gulmarg_meadow"], "gallery": [IMG["dal_wide"], IMG["pahalgam_valley"], IMG["shikara"]],
    "meta_title": "Kashmir Tour Package 4 Nights 5 Days | Budget Srinagar Gulmarg Pahalgam Trip",
    "meta_desc": "A compact, affordable Kashmir holiday package covering Srinagar, Gulmarg and Pahalgam in 4 nights 5 days. Ideal short trip to Kashmir with hotel, transfers and sightseeing included.",
    "intro": "Short on leave but long on wanderlust? Kashmir Express is a tightly-planned 4N/5D itinerary for travellers who want the highlights — Dal Lake, Gulmarg's meadows and Pahalgam's valleys — without a long trip. It's our most affordable full-circuit package and a favourite with working professionals and college friend groups looking for a quick Kashmir tour package from Srinagar airport back to Srinagar airport.",
    "highlights": [
        "Covers all 3 core destinations in just 4 nights",
        "1 night houseboat stay with shikara ride included",
        "Gulmarg Gondola Phase 1 cable car ride",
        "Pahalgam's Betaab Valley by local sightseeing cab",
        "Compact pricing — our lowest full-circuit package",
        "Private transfers throughout, no shared coaches",
    ],
    "itinerary": [
        ("Day 1 — Arrival & Srinagar Houseboat", "Airport pickup and transfer to your Dal Lake houseboat. Evening shikara ride included. Overnight on the houseboat."),
        ("Day 2 — Srinagar to Gulmarg", "Morning drive to Gulmarg, gondola ride to Kongdoori, a walk through the meadow and golf course, then return to Srinagar for the night."),
        ("Day 3 — Srinagar to Pahalgam", "Drive to Pahalgam via the saffron town of Pampore. Evening free to explore the Lidder riverside market. Overnight in Pahalgam."),
        ("Day 4 — Pahalgam Sightseeing & Return to Srinagar", "Local sightseeing cab to Betaab Valley and Aru Valley, then drive back to Srinagar for a final evening at the Boulevard promenade beside Dal Lake."),
        ("Day 5 — Departure", "Transfer to Srinagar Airport for your flight home."),
    ],
    "inclusions": [
        "4 nights accommodation (1 houseboat + 3 hotel), double sharing",
        "Daily breakfast and dinner",
        "All transfers and sightseeing in a private AC vehicle",
        "Shikara ride and Gulmarg Gondola Phase 1 ticket",
        "Driver allowance, parking and tolls",
    ],
    "exclusions": [
        "Airfare/train fare",
        "Gondola Phase 2, pony rides and adventure activities",
        "Lunches, personal expenses and tips",
        "GST and anything not listed under inclusions",
    ],
    "faqs": [
        ("Is 4 nights too short for Kashmir?", "It's the leanest version of our full-circuit itinerary — enough to see Srinagar, Gulmarg and Pahalgam, though each stop is a little brisker than our 5N/6D package. Great for a long weekend trip."),
        ("Can I add Sonmarg to this package?", "Yes, we can extend this to 5N/6D with a Sonmarg day trip for a small supplement — message us on WhatsApp and we'll requote instantly."),
    ],
},
{
    "slug": "kashmir-honeymoon-bliss-6n-7d",
    "title": "Kashmir Honeymoon Bliss",
    "duration": "6 Nights / 7 Days",
    "route": "Srinagar – Gulmarg – Pahalgam – Sonmarg",
    "category": "For Couples",
    "price": 31499, "old_price": 34999,
    "hero": IMG["shalimar_pav"], "gallery": [IMG["dal_sunset"], IMG["gulmarg_gondola2"], IMG["betaab2"]],
    "meta_title": "Kashmir Honeymoon Package | Romantic Kashmir Trip for Couples | Plan My Trip Kashmir",
    "meta_desc": "Kashmir honeymoon package with candlelight houseboat dinner, private shikara ride and couple-friendly hotels across Srinagar, Gulmarg, Pahalgam and Sonmarg. Best Kashmir tour packages for couples.",
    "intro": "Kashmir has been called Paradise on Earth by Mughal emperors who built entire gardens for the people they loved — it remains one of India's most romantic honeymoon destinations. This package is paced for couples: candlelight dinner on your houseboat, a private sunset shikara ride, quieter viewpoints away from the crowds, and couple-friendly rooms with lake or mountain views across all 4 destinations.",
    "highlights": [
        "2 nights luxury houseboat with candlelight dinner on Dal Lake",
        "Private sunset shikara ride for two",
        "Couple-friendly hotel rooms with valley or lake views",
        "Gulmarg Gondola ride with photo stop at Kongdoori",
        "Romantic riverside evening in Pahalgam by the Lidder",
        "Flexible pacing — no early-morning rush days",
    ],
    "itinerary": [
        ("Day 1 — Arrival & Welcome to Dal Lake", "Airport pickup, transfer to your deluxe houseboat, welcome drink and a relaxed first evening with a candlelight dinner served on the private deck."),
        ("Day 2 — Sunrise Shikara & Srinagar Gardens", "An easy morning shikara ride through the floating gardens, followed by a visit to Nishat Bagh and Shalimar Bagh. Free evening to stroll the Boulevard."),
        ("Day 3 — Gulmarg Day Trip", "Drive to Gulmarg for the gondola ride to Kongdoori. Couples can pause at the meadow for photographs before returning to Srinagar for a second night on the houseboat."),
        ("Day 4 — Srinagar to Pahalgam", "Scenic drive to Pahalgam through the saffron fields of Pampore. Check in to a valley-facing hotel and spend the evening beside the Lidder River."),
        ("Day 5 — Pahalgam Valleys", "Visit Betaab Valley and Aru Valley by local cab — both are popular film locations and offer quiet picnic spots for couples."),
        ("Day 6 — Sonmarg Excursion", "Half-day trip to Sonmarg for glacier and river views, then return to Srinagar for a final relaxed evening."),
        ("Day 7 — Departure", "Transfer to Srinagar Airport with our compliments and a printed trip memento."),
    ],
    "inclusions": [
        "6 nights accommodation (2 houseboat + 4 hotel), couple room",
        "Daily breakfast and dinner, including 1 candlelight dinner",
        "Private sunset shikara ride",
        "All transfers and sightseeing by private AC vehicle",
        "Gulmarg Gondola Phase 1 ticket",
        "Room décor on the houseboat for the first night",
    ],
    "exclusions": [
        "Airfare/train fare", "Gondola Phase 2 and adventure activities",
        "Lunches, personal expenses, spa/salon services",
        "GST and anything not mentioned under inclusions",
    ],
    "faqs": [
        ("Do you offer room décor for the honeymoon night?", "Yes, basic room décor (flowers and a welcome setup) is included on your first houseboat night. Premium décor and cake can be added for an extra charge."),
        ("Are the hotels couple-friendly for unmarried couples?", "We work with hotels that accept couples with a valid ID proof for both guests. Let us know your preference while booking and we'll confirm the right property."),
    ],
},
{
    "slug": "kashmir-family-wonders-6n-7d",
    "title": "Kashmir Family Wonders",
    "duration": "6 Nights / 7 Days",
    "route": "Srinagar – Gulmarg – Pahalgam – Sonmarg",
    "category": "Family Friendly",
    "price": 30499, "old_price": 33999,
    "hero": IMG["nishat_bagh"], "gallery": [IMG["dal_wide"], IMG["gulmarg_station"], IMG["aru_valley"]],
    "meta_title": "Kashmir Tour Packages for Family | Kids & Senior Friendly Kashmir Trip",
    "meta_desc": "Family-friendly Kashmir holiday package with relaxed pacing, comfortable hotels and easy sightseeing suited to kids and grandparents. Covers Srinagar, Gulmarg, Pahalgam and Sonmarg.",
    "intro": "Travelling with children or elderly parents needs a different rhythm — fewer early starts, easier walking distances and hotels with family rooms. Kashmir Family Wonders is designed exactly for that: a full 6-night circuit with buffer time built into each day, wheelchair/senior-friendly gondola access at Gulmarg, and a private vehicle throughout so nobody has to rush between stops.",
    "highlights": [
        "Relaxed daily pace with built-in rest time",
        "Family/triple rooms available across all hotels",
        "Kid-friendly shikara ride and pony rides in Pahalgam (optional)",
        "Gulmarg Gondola with easy boarding assistance",
        "Doctor-on-call support arranged if required",
        "Private vehicle with extra luggage space",
    ],
    "itinerary": [
        ("Day 1 — Arrival in Srinagar", "Airport pickup, houseboat check-in, and a gentle first evening — no sightseeing planned so the family can settle in after travel."),
        ("Day 2 — Srinagar Sightseeing", "Visit Nishat Bagh, Shalimar Bagh and Chashme Shahi at an easy pace, with plenty of photo stops and open lawns for children to run around."),
        ("Day 3 — Gulmarg Day Trip", "Gondola ride to Kongdoori (assistance provided for seniors), meadow walk, and an early return to Srinagar for rest."),
        ("Day 4 — Srinagar to Pahalgam", "Comfortable drive to Pahalgam with a stop at Pampore's saffron fields. Family hotel check-in with river-view rooms where available."),
        ("Day 5 — Pahalgam Valley Sightseeing", "Betaab Valley and Aru Valley by local cab, with time for pony rides and riverside picnics — a favourite day for children."),
        ("Day 6 — Sonmarg Excursion", "Half-day Sonmarg trip for glacier views, then an early return to Srinagar for packing and a relaxed final dinner."),
        ("Day 7 — Departure", "Timed airport transfer with buffer for check-in."),
    ],
    "inclusions": [
        "6 nights accommodation (2 houseboat + 4 hotel), family/triple rooms available",
        "Daily breakfast and dinner",
        "Private AC vehicle with extra boot space",
        "Shikara ride and Gulmarg Gondola Phase 1",
        "Assistance for elderly travellers at sightseeing points",
    ],
    "exclusions": [
        "Airfare/train fare", "Pony rides and adventure activities",
        "Lunches, personal expenses",
        "GST and anything not mentioned under inclusions",
    ],
    "faqs": [
        ("Is this package suitable for toddlers and grandparents together?", "Yes — this is exactly the itinerary we recommend for multi-generational family trips. We keep driving distances shorter per day and avoid back-to-back long drives."),
        ("Can you arrange a wheelchair or extra assistance?", "Yes, let us know in advance and we'll arrange wheelchair assistance at the airport and gondola stations, plus a driver briefed on any specific needs."),
    ],
},
{
    "slug": "srinagar-short-break-3n-4d",
    "title": "Srinagar City & Gardens Short Break",
    "duration": "3 Nights / 4 Days",
    "route": "Srinagar Only",
    "category": "Short Trip",
    "price": 14299, "old_price": 15999,
    "hero": IMG["dal_wide"], "gallery": [IMG["shalimar_arch"], IMG["shikara"], IMG["houseboat"]],
    "meta_title": "Srinagar Tour Package 3 Nights 4 Days | Srinagar Holiday Package with Houseboat",
    "meta_desc": "Srinagar-only holiday package with houseboat stay, shikara ride and Mughal Garden sightseeing. A quick srinagar trip package ideal for weekend travellers and business add-on trips.",
    "intro": "Not everyone has a week to spare. This Srinagar-focused package is built for travellers extending a business trip, a weekend getaway, or a first taste of Kashmir before deciding to come back for the full circuit. It covers the city's essential experiences — Dal Lake, the Mughal Gardens and the old city — from a comfortable houseboat or hotel base.",
    "highlights": [
        "2 nights houseboat + 1 night hotel in Srinagar",
        "Shikara ride through Dal Lake's floating gardens",
        "Nishat Bagh, Shalimar Bagh and Chashme Shahi",
        "Old city walk past Jamia Masjid and the riverside markets",
        "Optional half-day add-on to Gulmarg or Pahalgam",
    ],
    "itinerary": [
        ("Day 1 — Arrival & Houseboat Check-in", "Airport pickup and houseboat check-in on Dal Lake. Evening shikara ride to watch the sunset over the Zabarwan range."),
        ("Day 2 — Mughal Gardens & Shankaracharya Hill", "Full day covering Nishat Bagh, Shalimar Bagh, Chashme Shahi and the viewpoint at Shankaracharya Temple."),
        ("Day 3 — Old City & Local Markets", "Visit the old city's wooden architecture, Jamia Masjid and Hazratbal Shrine, followed by free time for shopping Pashmina shawls and papier-mâché souvenirs."),
        ("Day 4 — Departure", "Transfer to Srinagar Airport or railway station."),
    ],
    "inclusions": [
        "3 nights accommodation (2 houseboat + 1 hotel)",
        "Daily breakfast", "Airport transfers and city sightseeing by private vehicle",
        "1 hour shikara ride",
    ],
    "exclusions": [
        "Airfare/train fare", "Lunch and dinner (available on request at extra cost)",
        "Entry tickets to gardens (nominal, paid on the spot)",
        "GST and anything not mentioned under inclusions",
    ],
    "faqs": [
        ("Can I extend this into a Gulmarg or Pahalgam day trip?", "Yes, we offer this as an optional add-on for a day-trip supplement — just mention it while booking."),
        ("Is 3 nights enough to see Srinagar properly?", "It's enough to comfortably cover the Mughal Gardens, Dal Lake and the old city at a relaxed pace, without feeling rushed."),
    ],
},
{
    "slug": "gulmarg-snow-special-5n-6d",
    "title": "Gulmarg Snow Special",
    "duration": "5 Nights / 6 Days",
    "route": "Srinagar – Gulmarg (Winter)",
    "category": "Winter / December",
    "price": 25999, "old_price": 28999,
    "hero": IMG["gulmarg_cable"], "gallery": [IMG["gulmarg_gondola"], IMG["dal_sunset"], IMG["gulmarg_station"]],
    "meta_title": "Kashmir in December | Gulmarg Snow Package | Winter Kashmir Tour",
    "meta_desc": "Plan your Kashmir trip in December with our Gulmarg Snow Special package — snowfall, gondola rides and skiing at Asia's highest ski resort, plus Srinagar houseboat stay.",
    "intro": "December to February turns Gulmarg into one of Asia's premier snow destinations, with the Gondola climbing above snow-laden pine forests toward Apharwat Peak. This package is built around that season — extra nights in Gulmarg, warm-clothing guidance, and a flexible itinerary that adjusts to road and weather conditions, which is standard practice for any responsible Kashmir tour operator in winter.",
    "highlights": [
        "2 nights in Gulmarg during peak snow season",
        "Gulmarg Gondola Phase 1 (and Phase 2 optional, weather permitting)",
        "Skiing and snowboarding lessons available (paid add-on)",
        "Sledging in the snow meadows",
        "Srinagar houseboat stay with in-room heating",
        "Winter clothing and boot rental guidance provided",
    ],
    "itinerary": [
        ("Day 1 — Arrival in Srinagar", "Airport pickup and houseboat check-in with heated rooms. Evening at leisure."),
        ("Day 2 — Srinagar Sightseeing", "Visit Nishat Bagh, Shalimar Bagh and Chashme Shahi (some gardens have shorter winter hours)."),
        ("Day 3 — Drive to Gulmarg", "Transfer to Gulmarg, check in to a heated hotel and spend the afternoon walking through the snow-covered meadow."),
        ("Day 4 — Gondola & Snow Activities", "Full day for the Gondola ride, optional skiing lesson at the ski school, and sledging with local guides."),
        ("Day 5 — Gulmarg to Srinagar", "Morning at leisure in Gulmarg before returning to Srinagar for a final houseboat night."),
        ("Day 6 — Departure", "Transfer to Srinagar Airport."),
    ],
    "inclusions": [
        "5 nights accommodation (2 houseboat + 3 hotel) with heating",
        "Daily breakfast and dinner", "Private AC/heated vehicle for all transfers",
        "Gulmarg Gondola Phase 1 ticket",
    ],
    "exclusions": [
        "Airfare/train fare", "Ski/snowboard equipment and lessons",
        "Gondola Phase 2 ticket (subject to weather closures)",
        "Winter clothing rental, GST and anything not listed under inclusions",
    ],
    "faqs": [
        ("Does it always snow in Gulmarg in December?", "Snowfall in early December varies year to year — the heaviest, most reliable snow is usually late December through February. We'll advise honestly on current conditions when you enquire."),
        ("Is the road to Gulmarg safe in winter?", "Yes, the Tangmarg–Gulmarg road is regularly cleared by the authorities. Our drivers carry snow chains and we adjust timings around road advisories."),
    ],
},
{
    "slug": "jammu-kashmir-grand-tour-vaishno-devi-8n-9d",
    "title": "Jammu & Kashmir Grand Tour with Vaishno Devi",
    "duration": "8 Nights / 9 Days",
    "route": "Jammu – Katra (Vaishno Devi) – Srinagar – Gulmarg – Pahalgam – Sonmarg",
    "category": "Pilgrimage + Leisure",
    "price": 38499, "old_price": 42999,
    "hero": IMG["vaishno1"], "gallery": [IMG["vaishno2"], IMG["dal_sunset"], IMG["gulmarg_meadow"]],
    "meta_title": "Jammu and Kashmir Tour Package with Vaishno Devi | 8N/9D Grand Tour",
    "meta_desc": "Complete Jammu and Kashmir trip package combining Mata Vaishno Devi darshan at Katra with a full Kashmir valley circuit — Srinagar, Gulmarg, Pahalgam and Sonmarg. 8 nights 9 days.",
    "intro": "This is our most complete Jammu and Kashmir tour package — pairing the Mata Vaishno Devi pilgrimage at Katra with a full Kashmir valley holiday. It suits travellers who want both the spiritual significance of the shrine and the scenic circuit of Srinagar, Gulmarg, Pahalgam and Sonmarg in a single, well-sequenced trip.",
    "highlights": [
        "Mata Vaishno Devi darshan from Katra (trek or pony/palki at own cost)",
        "Full Kashmir circuit: Srinagar, Gulmarg, Pahalgam and Sonmarg",
        "Houseboat stay on Dal Lake with shikara ride",
        "Gulmarg Gondola Phase 1 ride",
        "Comfortable overnight halts, no same-day long-haul drives",
        "Single point of contact from Jammu arrival to Srinagar departure",
    ],
    "itinerary": [
        ("Day 1 — Arrival in Jammu, Transfer to Katra", "Pickup from Jammu Airport/Railway Station and drive to Katra, the base town for the Vaishno Devi shrine. Overnight in Katra."),
        ("Day 2 — Vaishno Devi Darshan", "Early trek (or optional pony/palki/helicopter at your own cost) to the shrine for darshan, returning to Katra by evening. Overnight in Katra."),
        ("Day 3 — Katra to Srinagar", "Scenic drive through the Jawahar Tunnel into the Kashmir Valley, arriving in Srinagar by evening. Houseboat check-in."),
        ("Day 4 — Srinagar Sightseeing", "Nishat Bagh, Shalimar Bagh, Chashme Shahi and a shikara ride on Dal Lake."),
        ("Day 5 — Srinagar to Gulmarg", "Day trip to Gulmarg for the Gondola ride and meadow walk, returning to Srinagar for the night."),
        ("Day 6 — Srinagar to Pahalgam", "Drive to Pahalgam via Pampore's saffron fields. Overnight in Pahalgam."),
        ("Day 7 — Pahalgam Valleys & Sonmarg", "Betaab and Aru Valley sightseeing, then a transfer toward Sonmarg for glacier views."),
        ("Day 8 — Return to Srinagar", "Free morning, last-minute shopping for Pashmina and saffron, and a farewell dinner."),
        ("Day 9 — Departure", "Transfer to Srinagar Airport."),
    ],
    "inclusions": [
        "8 nights accommodation (Katra hotel + Srinagar houseboat/hotel)",
        "Daily breakfast and dinner",
        "All ground transfers by private AC vehicle across Jammu and Kashmir",
        "Shikara ride and Gulmarg Gondola Phase 1",
    ],
    "exclusions": [
        "Airfare/train fare to Jammu and from Srinagar",
        "Vaishno Devi pony, palki or helicopter charges (paid directly)",
        "Lunches, personal expenses",
        "GST and anything not mentioned under inclusions",
    ],
    "faqs": [
        ("How difficult is the Vaishno Devi trek?", "The trek from Katra to the shrine is about 12–13 km on a well-paved path. It's a moderate climb — pony, palki (palanquin) and battery car options are available at your own cost for those who prefer not to walk the full distance."),
        ("How many days should be kept for Vaishno Devi alone?", "We recommend 2 full days in Katra — one for the ascent and darshan, one buffer for descent and rest, which this itinerary already includes."),
    ],
},
{
    "slug": "kashmir-ladakh-explorer-9n-10d",
    "title": "Kashmir with Ladakh Explorer",
    "duration": "9 Nights / 10 Days",
    "route": "Srinagar – Sonmarg – Kargil – Leh – Pangong – Gulmarg – Pahalgam",
    "category": "Adventure",
    "price": 49499, "old_price": 54999,
    "hero": IMG["pangong1"], "gallery": [IMG["leh1"], IMG["pangong3"], IMG["dal_wide"]],
    "meta_title": "Kashmir Ladakh Tour Package | Srinagar to Leh Trip | 9N/10D",
    "meta_desc": "Combined Kashmir and Ladakh tour package — Srinagar, Sonmarg, Kargil, Leh and Pangong Lake, plus Gulmarg and Pahalgam. A complete Jammu and Kashmir travel and tourism circuit for adventure travellers.",
    "intro": "For travellers who want both the green valleys of Kashmir and the high-altitude desert of Ladakh in one trip, this is our flagship long-format package. You cross the dramatic Zoji La pass overland from Sonmarg into Kargil, spend days acclimatising and exploring around Leh, drive out to the turquoise expanse of Pangong Lake, then loop back through Kashmir's Gulmarg and Pahalgam before flying out of Srinagar.",
    "highlights": [
        "Overland crossing via Zoji La from Kashmir into Ladakh",
        "2 nights at Pangong Tso, one of the world's highest saline lakes",
        "Leh local sightseeing with built-in acclimatisation day",
        "Gulmarg and Pahalgam covered on the return leg",
        "Srinagar houseboat stay with shikara ride",
        "Experienced high-altitude drivers and oxygen support on request",
    ],
    "itinerary": [
        ("Day 1 — Arrival in Srinagar", "Airport pickup, houseboat check-in, evening shikara ride."),
        ("Day 2 — Srinagar Sightseeing", "Mughal Gardens and Dal Lake, preparing for the Ladakh leg ahead."),
        ("Day 3 — Srinagar to Kargil via Sonmarg & Zoji La", "Long scenic drive over the Zoji La pass into Ladakh's high-altitude terrain, overnight in Kargil."),
        ("Day 4 — Kargil to Leh", "Drive through Lamayuru's moonland landscape and the confluence of the Indus and Zanskar rivers, arriving in Leh. Rest evening for acclimatisation."),
        ("Day 5 — Leh Acclimatisation & Local Sightseeing", "Easy day covering Shanti Stupa, Leh Palace and the main market at a gentle pace to help the body adjust to altitude."),
        ("Day 6 — Leh to Pangong Lake", "Drive via Chang La pass to Pangong Tso. Overnight by the lake in a camp or guesthouse."),
        ("Day 7 — Pangong to Leh", "Morning by the lake before the return drive to Leh."),
        ("Day 8 — Leh to Srinagar (fly or overland by arrangement)", "Return toward Kashmir, with an overnight halt planned around road conditions."),
        ("Day 9 — Gulmarg or Pahalgam Day Trip", "A final Kashmir valley day — Gulmarg Gondola or Pahalgam sightseeing, based on your arrival time."),
        ("Day 10 — Departure", "Transfer to Srinagar Airport."),
    ],
    "inclusions": [
        "9 nights accommodation across Srinagar, Kargil, Leh, Pangong and Gulmarg/Pahalgam",
        "Daily breakfast and dinner",
        "All ground transfers by private vehicle suited to high-altitude roads",
        "Inner Line Permit assistance for Pangong Lake",
        "Shikara ride and Gulmarg Gondola Phase 1",
    ],
    "exclusions": [
        "Airfare/train fare", "Oxygen cylinder or medical evacuation if required",
        "Lunches, personal expenses", "GST and anything not mentioned under inclusions",
    ],
    "faqs": [
        ("Is this trip physically demanding?", "The Ladakh leg involves high-altitude travel (Leh sits at about 3,500m). We build in a dedicated acclimatisation day and recommend travellers with heart or breathing conditions consult a doctor before booking."),
        ("What is the best season for this combined trip?", "June to September, when the Srinagar–Leh highway via Zoji La is fully open and Pangong Lake is accessible without snow closures."),
    ],
},
{
    "slug": "srinagar-houseboat-shikara-2n-3d",
    "title": "Kashmir Houseboat & Shikara Experience",
    "duration": "2 Nights / 3 Days",
    "route": "Srinagar Only",
    "category": "Quick Getaway",
    "price": 8999, "old_price": 9999,
    "hero": IMG["houseboat"], "gallery": [IMG["shikara"], IMG["dal_sunset"], IMG["nishat_bagh"]],
    "meta_title": "Srinagar Houseboat Package | Dal Lake Shikara Ride Booking | 2N/3D",
    "meta_desc": "Book a Srinagar houseboat stay with shikara ride on Dal Lake — a quick 2 nights 3 days Kashmir getaway, ideal as a standalone trip or add-on to another itinerary.",
    "intro": "Sometimes all you want is the Dal Lake experience itself — waking up to the sound of water against a wooden hull, floating markets at dawn, and a slow shikara ride at sunset. This compact package is built purely around that, and works equally well as a standalone weekend trip or as an add-on before/after another itinerary you're already booking with us or elsewhere.",
    "highlights": [
        "2 nights aboard a traditional Kashmiri houseboat",
        "Sunrise floating market shikara ride (optional, early start)",
        "Sunset shikara ride included",
        "Half-day Srinagar city and Mughal Garden tour",
        "Flexible add-on to any longer Kashmir itinerary",
    ],
    "itinerary": [
        ("Day 1 — Arrival & Houseboat Check-in", "Airport pickup, houseboat check-in, welcome tea, and an evening shikara ride on Dal Lake."),
        ("Day 2 — City & Gardens", "Half-day visit to Nishat Bagh and Shalimar Bagh, with the afternoon free to relax on the houseboat deck or explore the old city."),
        ("Day 3 — Departure", "Optional early-morning floating market shikara ride, then transfer to the airport."),
    ],
    "inclusions": [
        "2 nights houseboat accommodation, double sharing",
        "Daily breakfast", "Airport transfers", "2 shikara rides (sunset + optional sunrise)",
    ],
    "exclusions": [
        "Airfare/train fare", "Lunch and dinner", "Garden entry tickets",
        "GST and anything not mentioned under inclusions",
    ],
    "faqs": [
        ("Can this be combined with another package?", "Yes — many guests book this houseboat stay before or after a Gulmarg/Pahalgam itinerary, especially when arriving on an early flight and wanting to settle in gently."),
        ("Is there Wi-Fi and hot water on the houseboat?", "Most houseboats offer Wi-Fi and hot water; we confirm exact amenities of your specific houseboat at the time of booking so there are no surprises."),
    ],
},
{
    "slug": "best-of-kashmir-luxury-tour-6n-7d",
    "title": "Best of Kashmir Luxury Tour",
    "duration": "6 Nights / 7 Days",
    "route": "Srinagar – Gulmarg – Pahalgam – Sonmarg",
    "category": "Premium",
    "price": 43299, "old_price": 47999,
    "hero": IMG["shalimar_arch"], "gallery": [IMG["dal_sunset"], IMG["gulmarg_cable"], IMG["pahalgam_peaks"]],
    "meta_title": "Best Kashmir Tour Packages | Luxury Kashmir Trip 6N/7D | Plan My Trip Kashmir",
    "meta_desc": "Our premium, best-rated Kashmir tour package with 5-star houseboats, boutique hotels and a private guide across Srinagar, Gulmarg, Pahalgam and Sonmarg. Best tour packages for Kashmir, upgraded.",
    "intro": "This is our top-tier itinerary for travellers who want the full Kashmir circuit without compromising on comfort — deluxe/luxury-category houseboats, boutique hotels in Gulmarg and Pahalgam, a private guide for the Srinagar gardens, and a slower, more curated pace than our standard packages.",
    "highlights": [
        "Deluxe/luxury houseboat category with premium interiors",
        "Boutique 4-star hotel category in Gulmarg and Pahalgam",
        "Private licensed guide for Srinagar's Mughal Gardens",
        "Early-access Gulmarg Gondola slot to avoid queues",
        "Curated dining recommendations, including Wazwan multi-course dinner",
        "Priority airport meet-and-greet",
    ],
    "itinerary": [
        ("Day 1 — Arrival & Luxury Houseboat", "Priority airport pickup and check-in to a deluxe-category houseboat, followed by a private sunset shikara ride."),
        ("Day 2 — Srinagar with a Private Guide", "A private guide walks you through Nishat Bagh, Shalimar Bagh and Chashme Shahi with historical context on the Mughal era."),
        ("Day 3 — Gulmarg (Early Access)", "An early departure secures an early Gondola slot, avoiding the mid-day queues, followed by a boutique hotel check-in for the night."),
        ("Day 4 — Gulmarg to Pahalgam", "Scenic transfer to Pahalgam, checking into a boutique riverside property."),
        ("Day 5 — Pahalgam Valleys", "Private cab to Betaab and Aru Valley, with a riverside picnic lunch arranged on request."),
        ("Day 6 — Sonmarg & Return to Srinagar", "Morning at Sonmarg, then back to Srinagar for a Wazwan multi-course dinner experience on your final night."),
        ("Day 7 — Departure", "Priority transfer to Srinagar Airport."),
    ],
    "inclusions": [
        "6 nights in deluxe/luxury houseboat + boutique 4-star hotels",
        "Daily breakfast and dinner, including one Wazwan dinner experience",
        "Private guide for Srinagar sightseeing",
        "Private AC vehicle throughout, early Gondola access",
        "Priority airport meet-and-greet",
    ],
    "exclusions": [
        "Airfare/train fare", "Gondola Phase 2 ticket",
        "Alcoholic beverages, spa services", "GST and anything not mentioned under inclusions",
    ],
    "faqs": [
        ("What makes this different from your standard package?", "Higher accommodation category, a private licensed guide, priority gondola access, and a curated dining experience — the itinerary covers the same destinations as our Paradise Getaway package but at a noticeably more comfortable pace and quality level."),
        ("Can I upgrade an existing booking to this luxury tier?", "Yes, tell us your travel dates and we'll requote the price difference to upgrade hotel and houseboat categories."),
    ],
},
]

PACKAGES_SHORT_FOR_FOOTER = PACKAGES[:5]
