DESTINATIONS = [
{
    "slug": "srinagar",
    "title": "Srinagar",
    "tagline": "Dal Lake, Houseboats & the Mughal Gardens",
    "hero": IMG["dal_sunset"],
    "gallery": [IMG["nishat_bagh"], IMG["shikara"], IMG["shalimar_arch"]],
    "meta_title": "Srinagar Tourism | Places to Visit, Houseboat Booking & Sightseeing Guide",
    "meta_desc": "Complete Srinagar travel guide — Dal Lake houseboats, Mughal Gardens, shikara rides and sightseeing itinerary. Book your Srinagar holiday package with Plan My Trip Kashmir.",
    "body": [
        "Srinagar is the summer capital of Jammu & Kashmir and the starting point for almost every Kashmir tour package. The city is built around Dal Lake, where rows of ornately carved houseboats sit moored beside floating vegetable gardens, and shikaras — the flat, cushioned gondolas of Kashmir — glide between them from before sunrise until after dark.",
        "Beyond the lake, Srinagar holds four Mughal-era gardens worth a full day on their own: Nishat Bagh and Shalimar Bagh on Dal Lake's eastern shore, and Chashme Shahi and Pari Mahal on the slopes above. Each was laid out on the classic charbagh plan — terraced lawns, a central water channel, and chinar trees planted centuries ago that now tower over the paths.",
        "The old city, on the western bank of the Jhelum River, is a different Srinagar entirely — wooden latticed houses, the 14th-century Jamia Masjid with its 370 deodar pillars, and narrow lanes where papier-mâché and Pashmina workshops still operate as they have for generations.",
    ],
    "attractions": [
        ("Dal Lake & Houseboats", "Stay a night on a traditional houseboat and explore the lake's floating gardens and market by shikara."),
        ("Nishat Bagh", "The largest of Srinagar's Mughal gardens, built in 1633 on the eastern shore of Dal Lake."),
        ("Shalimar Bagh", "Built by Emperor Jahangir in 1619, considered the high point of Mughal garden design in Kashmir."),
        ("Shankaracharya Temple", "A hilltop temple offering the best panoramic view of the city and lake."),
        ("Old City & Jamia Masjid", "Wooden architecture, historic mosques and the traditional handicraft markets."),
        ("Hazratbal Shrine", "A revered shrine on Dal Lake's northern shore, striking in white marble."),
    ],
    "best_time": "March to October for gardens and mild weather; December to February for a quieter, snow-dusted city.",
    "how_to_reach": "Srinagar International Airport connects to Delhi, Mumbai, Bengaluru, Chandigarh and other major Indian cities year-round. Srinagar is also the standard start and end point for road itineraries covering Gulmarg, Pahalgam and Sonmarg.",
    "related_packages": ["kashmir-paradise-getaway-5n-6d", "srinagar-short-break-3n-4d", "srinagar-houseboat-shikara-2n-3d"],
},
{
    "slug": "gulmarg",
    "title": "Gulmarg",
    "tagline": "Meadow of Flowers & Asia's Highest Gondola",
    "hero": IMG["gulmarg_cable"],
    "gallery": [IMG["gulmarg_gondola"], IMG["gulmarg_meadow"], IMG["gulmarg_station"]],
    "meta_title": "Gulmarg Tourism Guide | Gondola, Skiing & Best Time to Visit",
    "meta_desc": "Gulmarg travel guide — the Gulmarg Gondola cable car, skiing season, meadow walks and how to plan your Gulmarg day trip from Srinagar.",
    "body": [
        "Gulmarg — literally 'meadow of flowers' — sits at around 2,650m in the Pir Panjal range, about 50km from Srinagar. In summer it's a rolling green meadow ringed by pine forest and used as a golf course at one of the highest golf greens in the world; in winter it transforms into one of Asia's premier ski destinations.",
        "The Gulmarg Gondola is the main draw for most visitors — a two-stage cable car that climbs from Gulmarg to Kongdoori (Phase 1) and on to Apharwat Peak at roughly 3,980m (Phase 2, subject to weather). The views from the top, across snow-covered ridgelines toward the Line of Control, are some of the most dramatic in the Kashmir Valley.",
        "Most Kashmir tour packages treat Gulmarg as a day trip from Srinagar, though winter travellers — especially skiers — often prefer to stay 1–2 nights to make the most of the slopes and avoid a long return drive after a cold day on the mountain.",
    ],
    "attractions": [
        ("Gulmarg Gondola", "A two-phase cable car to Kongdoori and Apharwat Peak, among the highest in the world."),
        ("Gulmarg Golf Course", "One of the highest green golf courses globally, playable in the summer season."),
        ("Skiing & Snowboarding", "December to February brings reliable snow and a functioning ski school for beginners."),
        ("St. Mary's Church", "A small colonial-era church set among the pines."),
        ("Alpather Lake", "A high-altitude glacial lake, reachable by trek in the summer months."),
    ],
    "best_time": "April to June for meadows and mild weather; December to February for snow, skiing and gondola views over snow-covered peaks.",
    "how_to_reach": "About 50km / 1.5 hours by road from Srinagar via Tangmarg. All our packages include this transfer by private AC vehicle.",
    "related_packages": ["kashmir-paradise-getaway-5n-6d", "gulmarg-snow-special-5n-6d", "best-of-kashmir-luxury-tour-6n-7d"],
},
{
    "slug": "pahalgam",
    "title": "Pahalgam",
    "tagline": "Valley of Shepherds — Betaab, Aru & the Lidder River",
    "hero": IMG["betaab1"],
    "gallery": [IMG["aru_valley"], IMG["pahalgam_valley"], IMG["betaab2"]],
    "meta_title": "Pahalgam Tourism Guide | Betaab Valley, Aru Valley & Sightseeing",
    "meta_desc": "Pahalgam travel guide covering Betaab Valley, Aru Valley, Chandanwari and the Lidder River — everything you need for your Pahalgam sightseeing day.",
    "body": [
        "Pahalgam, meaning 'Valley of Shepherds', sits at the confluence of the Lidder River's east and west branches, about 90km from Srinagar. It's greener and gentler than Gulmarg's alpine terrain — pine and deodar forest, riverside meadows, and a handful of side valleys that have made it a favourite filming location for decades.",
        "Betaab Valley, renamed after the 1983 Bollywood film shot here, and Aru Valley, a quieter meadow used as a base camp for treks further into the mountains, are the two most-visited stops. Both are a short local-taxi ride from Pahalgam's main market, and both are included in every Pahalgam sightseeing plan we run.",
        "Pahalgam is also the traditional base camp for the Amarnath Yatra pilgrimage in July–August, when the town's infrastructure shifts to support pilgrims heading to the cave shrine. Outside yatra season, it's simply one of Kashmir's most relaxed valley towns.",
    ],
    "attractions": [
        ("Betaab Valley", "A lush meadow flanked by pine forest, 15km from Pahalgam market."),
        ("Aru Valley", "A quieter meadow and trekking base camp, known for alpine flowers in season."),
        ("Chandanwari", "The starting point of the Amarnath Yatra trek route, also a popular sledging spot in winter."),
        ("Lidder River", "A trout-filled mountain river running through the town, popular for riverside walks."),
        ("Baisaran Valley", "A meadow reachable by pony ride, sometimes called 'Mini Switzerland'."),
    ],
    "best_time": "March to June for wildflowers and mild weather; September to November for autumn colours and fewer crowds.",
    "how_to_reach": "About 90km / 2.5–3 hours by road from Srinagar, usually combined with a stop at the Pampore saffron fields en route.",
    "related_packages": ["kashmir-paradise-getaway-5n-6d", "kashmir-honeymoon-bliss-6n-7d", "kashmir-family-wonders-6n-7d"],
},
{
    "slug": "sonmarg-and-offbeat-kashmir",
    "title": "Sonmarg & Offbeat Kashmir",
    "tagline": "Thajiwas Glacier, Doodhpathri and Yusmarg",
    "hero": IMG["pahalgam_peaks"],
    "gallery": [IMG["dal_wide"], IMG["pahalgam_autumn"], IMG["gulmarg_meadow"]],
    "meta_title": "Sonmarg Travel Guide | Thajiwas Glacier & Offbeat Kashmir Destinations",
    "meta_desc": "Sonmarg and offbeat Kashmir guide — Thajiwas Glacier, Doodhpathri and Yusmarg meadows. Ideal add-ons to any Kashmir trip package for travellers who want to go beyond the usual circuit.",
    "body": [
        "Sonmarg — the 'meadow of gold' — sits at around 2,800m on the route toward Ladakh via Zoji La, roughly 80km from Srinagar. It's the last major stop before the high Himalaya proper, with the Sindh River running alongside the road and the Thajiwas Glacier a short pony ride or walk from the main viewpoint.",
        "Beyond the standard Srinagar–Gulmarg–Pahalgam circuit, Kashmir has a set of quieter meadows that most first-time visitors never see. Doodhpathri ('valley of milk'), about 42km from Srinagar, is a wide, flat meadow crossed by a small stream, popular for picnics and largely free of the crowds found at Gulmarg. Yusmarg, similarly close, is a forested meadow with a small trek up to Nilagrad's glacial stream.",
        "We build these into custom itineraries on request — they're not part of our standard packages by default, but travellers who've already done Kashmir once, or who simply want fewer crowds, often ask us to swap a day for Doodhpathri or Yusmarg instead.",
    ],
    "attractions": [
        ("Thajiwas Glacier", "A glacier viewpoint near Sonmarg, reachable by a short walk or pony ride."),
        ("Zoji La Pass", "The high mountain pass connecting Kashmir to Ladakh, usually open June–October."),
        ("Doodhpathri", "A quiet, less-visited meadow about 42km from Srinagar, ideal for a peaceful day trip."),
        ("Yusmarg", "A forested meadow with the Doodh Ganga stream and views of the Pir Panjal range."),
    ],
    "best_time": "May to September, when the Zoji La road is open and the meadows are green.",
    "how_to_reach": "Sonmarg is about 80km / 2.5 hours from Srinagar; Doodhpathri and Yusmarg are each roughly 40–45km and make easy half-day trips.",
    "related_packages": ["kashmir-paradise-getaway-5n-6d", "kashmir-honeymoon-bliss-6n-7d", "kashmir-ladakh-explorer-9n-10d"],
},
{
    "slug": "leh-ladakh",
    "title": "Leh-Ladakh",
    "tagline": "High-Altitude Desert & Pangong Lake",
    "hero": IMG["pangong2"],
    "gallery": [IMG["leh1"], IMG["leh2"], IMG["pangong3"]],
    "meta_title": "Leh Ladakh Tour Guide | Pangong Lake, Best Time & How to Reach from Kashmir",
    "meta_desc": "Leh-Ladakh travel guide for travellers combining it with a Kashmir trip — Pangong Lake, Leh sightseeing, acclimatisation tips and the overland route via Zoji La.",
    "body": [
        "Ladakh sits on the far side of the Zoji La pass from Kashmir — a high-altitude desert of bare mountains, Buddhist monasteries and turquoise lakes that feels like a different country from the green valley below. Leh, the main town, sits at roughly 3,500m, which means every itinerary here needs to account for acclimatisation before any serious sightseeing.",
        "Pangong Tso, made famous by Bollywood, is the highlight for most travellers — a 134km-long saline lake that changes colour through the day, with roughly 60% of it lying across the border in Chinese-administered territory. It's reached via the Chang La pass, one of the world's highest motorable roads.",
        "We only offer Ladakh as part of our combined Kashmir–Ladakh Explorer package, run overland via Sonmarg and the Zoji La pass — a genuinely spectacular drive, but one that's only feasible when the pass is open, typically June through early October.",
    ],
    "attractions": [
        ("Pangong Tso", "A vast, colour-shifting saline lake at over 4,200m, reached via Chang La pass."),
        ("Leh Palace", "A 17th-century royal palace overlooking Leh town, modelled on Lhasa's Potala Palace."),
        ("Shanti Stupa", "A white-domed Buddhist stupa with panoramic views over Leh."),
        ("Lamayuru Monastery", "One of Ladakh's oldest monasteries, set amid a striking 'moonland' landscape."),
    ],
    "best_time": "June to September, when the Srinagar–Leh highway via Zoji La is open and temperatures are manageable.",
    "how_to_reach": "Overland from Srinagar via Sonmarg and Zoji La (as part of our Kashmir with Ladakh Explorer package), or by direct flight into Leh Airport from Delhi.",
    "related_packages": ["kashmir-ladakh-explorer-9n-10d"],
},
]

DESTINATIONS_SHORT_FOR_FOOTER = DESTINATIONS[:5]
